
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 站点基本信息配置
title: 胡一刀的个人博客
subtitle: May the force be with you
description: Talk is cheap. Show me your code.
keywords: 博客
author: sonnyhcl
language: zh-CN
timezone: Asia/Shanghai 

# 站点域名配置
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://sonnyhcl.com/
root: /
## 很多博客都会选择在前面加上:year/:month/:day/:title/作为链接，个人喜好问题
permalink: :title/

# 文件夹配置
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

# 博文配置
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: # Open external links in new tab
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: true
  
# 主页配置
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# 分类与标签
default_category: Tech
category_map:
tag_map:

# 日期时间格式
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# 分页设置
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# 扩展插件
## Plugins: https://hexo.io/plugins/
Plugins: hexo-generate-feed

# 插件：阅读时间估计
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true

# 主题选择
## Themes: https://hexo.io/themes/
theme: next
