name: CI

on:
  push:
    branches: [ source ]

env:
  GIT_USER: Chenglong Hu
  GIT_EMAIL: sonnyhcl@gmail.com
  DEPLOY_REPO: sonnyhcl/sonnyhcl.github.io
  DEPLOY_BRANCH: master

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          ref: source
      - name: Checkout hexo-theme-next
      # run: git clone https://github.com/theme-next/hexo-theme-next --branch v7.8.0 themes/next --single-branch
        run: git clone https://github.com/theme-next/hexo-theme-next themes/next
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
